services:
  postgres:
    image: postgres:16
    container_name: pg-ariadna
    restart: unless-stopped
    environment:
      POSTGRES_USER: ariadna
      POSTGRES_PASSWORD: ariadna
      POSTGRES_DB: ariadna
      TZ: Europe/Moscow
      LANG: en_US.utf8
    ports:
      - "5435:5432"
    # ❗ заменили bind-mount на named volume
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Скрипты инициализации можно оставить bind-mount (read-only ок для Windows)
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ariadna -d ariadna"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./back
    container_name: pg-ariadna-back
    restart: unless-stopped
    network_mode: host
    environment:
      DATABASE_DSN: "host=127.0.0.1 user=ariadna password=ariadna dbname=ariadna port=5435 sslmode=disable"
      ADMIN_LOGIN: "admin"
      ADMIN_PASSWORD: "admin"
      INSTRUMENTS: "TH2690-1=192.168.1.150:45454,TH2690-2=192.168.1.151:45454,TH2690-3=192.168.1.152:45454"
      CAMERAS: "DS-H104GA=rtsp://admin:Ariadna25@192.168.1.64:554/Streaming/Channels/101"
      MINIO_ENDPOINT: "127.0.0.1:9000"
      MINIO_ACCESS_KEY: "ariadna"
      MINIO_SECRET_KEY: "ariadna123"
      MINIO_BUCKET: "experiments"
    volumes:
      - uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started

  minio:
    image: minio/minio:latest
    container_name: pg-ariadna-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ariadna
      MINIO_ROOT_PASSWORD: ariadna123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  frontend:
    build:
      context: ./front
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:8080"
        NEXT_PUBLIC_ROWS_PER_PAGE: "20"
    container_name: pg-ariadna-front
    restart: unless-stopped
    ports:
      - "8070:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  uploads:
  miniodata:
